### ISSUE TITLE
Not buildable on VS2019 v16.8

### ISSUE THREAD

**Issue by isral** [neildanson/MicroCS#1]
The packages has missing files, so I extract *.nupkg manually.
After that VS asked for FSharp.Core.dll 4.3.0.0.
I add the reference manually but still not buildable.

**Comment by neildanson** [comment]
I'll take a look shortly. Not built this for a while as it was a toy project a few years back. Will see if I can make the monster live again!

**Comment by isral** [comment]
BTW what is the name of this design pattern where you have parameters in different kind
...
let rec buildType types <ins>**classes interfaces structs enums**</ins> = 
...
let classes = body |> List.map (fun <ins>**(t, , , )**</ins></span> -> t) |> List.collect id
...

**Comment by neildanson** [comment]
Not sure I follow the question?

It's basically a fold/accumulator, where the underlined items start as empty lists, and accumulate values with each recursive call. 

But I'm not sure if thats the answer you are after?

**Comment by neildanson** [comment]
Thanks to @isral - closed by https://github.com/neildanson/MicroCS/pull/2
